name: print github action environment variable
run-name: ${{ github.actor }} is testing out github actions
on: [push]
jobs:
  Explore-Gihub-actoions:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Event Name:  $GITHUB_EVENT_NAME"
          echo "Actor name:  $GITHUB_ACTOR"
          echo "Repo Name:   $GITHUB_REPOSITORY"
          echo "SHA name:    $GITHUB_SHA"
          
          echo "branch Name:  $GITHUB_REF_NAME"
      
